dist: trusty
language: python
python:
  - "3.6"
before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - "pip install -U coverage flake8 'isort<4.3.5' pylint pytest pytest-cov"
  - "pip install -U -r requirements/base.txt"
script:
  - "pytest -vs --cov=jishaku --cov-report term-missing:skip-covered"
  - "pip install -U ."
  - "rm -rf jishaku"
  - "pytest -vs"
